### ISSUE TITLE
Add gitignore

### ISSUE THREAD

**Issue by drhuang0922** [richard000031/Notepad#1]
Usually, to reduce the scale of codebase and avoid some meaningless modifications while the version of modules upgrading. we will add the folder node modules into git ignore. Thus your commit will only focus on the changing in functionalities. 

Trivial answer to why node module in gitignore:
https://qr.ae/prShRj

gitignore template generator:
https://mrkandreev.name/snippets/gitignore-generator/

**Comment by richard000031** [comment]
okay, I already add gitignore file
